language: c++
before_script:
  - mkdir -p bin
script:
  - ./make_fixtures.py
  - gcc -o bin/test_bqint8 -DBQINT_WORD_BITS=8 test_bqint.c
  - gcc -o bin/test_bqint16 -DBQINT_WORD_BITS=16 test_bqint.c
  - gcc -o bin/test_bqint32 -DBQINT_WORD_BITS=32 test_bqint.c
  - bin/test_bqint8 bin/fixtures.bin
  - bin/test_bqint16 bin/fixtures.bin
  - bin/test_bqint32 bin/fixtures.bin
notifications:
  email: false
